## Numpy: Numeric computing library Exercise by CheddarAnalyst

In [4]:
import sys
import numpy as np

## Basic Numpy Array

In [5]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [6]:
a = np.array([1,2,3,4])

In [7]:
b = np.array([0, .5, 1, .5, 2])

# Giving elements in each Np

In [8]:
a[0], a[1], a[2]

(1, 2, 3)

In [9]:
b[1], b[2], b[3]

(0.5, 1.0, 0.5)

# Slicing

In [11]:
a[0:]

array([1, 2, 3, 4])

In [12]:
a[1:]

array([2, 3, 4])

In [13]:
a[1:4]

array([2, 3, 4])

In [14]:
a[1:2]

array([2])

In [15]:
a[1:-1]

array([2, 3])

In [16]:
a[::2]

array([1, 3])

# Multindexing

In [17]:
b

array([0. , 0.5, 1. , 0.5, 2. ])

In [18]:
b[0], b[2], b[-1]

(0.0, 1.0, 2.0)

In [19]:
b[[0, 2, -1]]

array([0., 1., 2.])

# Array Types

In [20]:
a

array([1, 2, 3, 4])

In [22]:
a.dtype

dtype('int32')

In [23]:
b

array([0. , 0.5, 1. , 0.5, 2. ])

In [25]:
b.dtype

dtype('float64')

# Creating Integers using a float type

In [30]:
np.array([1,2,3,4], dtype=np.float64)

array([1., 2., 3., 4.])

In [33]:
np.array([1,2,3,4], dtype=np.int32)

array([1, 2, 3, 4])

In [34]:
c = np.array(['a', 'b','c'])

In [35]:
c.dtype

dtype('<U1')

In [36]:
d = np.array([{'a': 1}, sys])

In [38]:
d.dtype

dtype('O')

# Dimensions and shapes

We can make a 2 dimensional np using matrices

In [39]:
A = np.array([
    [1,2,3],
    [4,5,6]
])

In [40]:
A.shape

(2, 3)

In [41]:
A.ndim

2

In [42]:
A.size

6

Lets make a 3 Dimensional 

In [43]:
B = np.array([
    [
        [12,10,16],
    [9,8,7],
    ],
    [
    [6,5,4],
    [3,2,1]
    ]
])

In [44]:
B

array([[[12, 10, 16],
        [ 9,  8,  7]],

       [[ 6,  5,  4],
        [ 3,  2,  1]]])

In [45]:
B.shape

(2, 2, 3)

In [46]:
B.ndim

3

In [47]:
B.size

12

If the shape isn't consistent,it's just fallback to regular python objects:

In [48]:
C = np.array([
    [
        [12,11,18],
        [9,8,7],
    ],
    [
        [6,5,4]
    ]
])

C:\Users\Nicho\AppData\Local\Temp/ipykernel_21668/2793226495.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  C = np.array([


In [49]:
C.dtype

dtype('O')

In [50]:
C.shape

(2,)

In [51]:
C.ndim

1

In [52]:
C.size

2

In [53]:
type(C[0])

list

# Indexing and Slicing of Matrices

In [54]:
#Square matrix
A = np.array([
#.  0. 1. 2.    
    [1,2,3],#0
    [4,5,6],#1
    [7,8,9] #2
])

Row 1 selection:

In [55]:
A[1]

array([4, 5, 6])

Getting first element of the second row:

In [58]:
A[1][0]

4

Using the following syntax ,we will have to get passed the following dimensions # A[d1, d2, d3, d4]

In [59]:
A[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [60]:
A[:, :2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [61]:
A[:2, 2:]

array([[3],
       [6]])

In [62]:
A[:3, 1:]

array([[2, 3],
       [5, 6],
       [8, 9]])

In [63]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Modification Assigning:

In [64]:
A[1] = np.array([10,10,10])

In [65]:
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [ 7,  8,  9]])

Using an expand operation:

In [66]:
A[2] = 99

In [67]:
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [99, 99, 99]])

# Summary Statistics

In [4]:
import sys
import numpy as np

In [5]:
a = np.array([1,2,3,4])

In [6]:
a.sum()

10

In [7]:
a.mean()

2.5

In [8]:
a.std()

1.118033988749895

In [9]:
a.var()

1.25

In [10]:
A = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [11]:
A.sum()

45

In [12]:
A.mean()

5.0

In [13]:
A.std()

2.581988897471611

In [14]:
A.var()

6.666666666666667

Calculating matrix per axis; implying 0=Horizontal axis 1=Vertical axis

In [15]:
A.sum(axis=0)

array([12, 15, 18])

In [17]:
A.sum(axis=1)

array([ 6, 15, 24])

In [18]:
A.mean(axis=0)

array([4., 5., 6.])

In [19]:
A.mean(axis=1)

array([2., 5., 8.])

In [20]:
A.std(axis=0)

array([2.44948974, 2.44948974, 2.44948974])

In [21]:
A.std(axis=1)

array([0.81649658, 0.81649658, 0.81649658])

# Broadcasting and Vectorized operations

In [22]:
a =np.arange(4)

In [23]:
a

array([0, 1, 2, 3])

Broadcasting to each one of the individual elements in the arrays:

In [24]:
a+10

array([10, 11, 12, 13])

In [25]:
a*10

array([ 0, 10, 20, 30])

In [26]:
a

array([0, 1, 2, 3])

In [28]:
a += 100

In [29]:
a

array([100, 101, 102, 103])

In [31]:
l =[0,1,2,3]

In [32]:
[i * 10 for i in l]

[0, 10, 20, 30]

In [33]:
a = np.arange(4)

In [34]:
a

array([0, 1, 2, 3])

In [35]:
b = np.array([10,10,10,10])

In [36]:
a + b

array([10, 11, 12, 13])

In [37]:
a * b

array([ 0, 10, 20, 30])

# Boolean Arrays

## Also called (Masks)

In [39]:
a = np.arange(4)

In [40]:
a

array([0, 1, 2, 3])

The first way for making your selection:

In [41]:
a[0], a[-1]

(0, 3)

Second way of selection which is multi indexing:

In [44]:
a[[0, -1]]

array([0, 3])

Third way of selection is through Boolean Arrays:
True = Selected

False = Unselected

In [46]:
a[[True,False,False,True]]

array([0, 3])

In [47]:
a >= 2

array([False, False,  True,  True])

In [49]:
a[a >= 2 ]

array([2, 3])

In [50]:
a.mean()

1.5

In [51]:
a[a >a.mean()]

array([2, 3])

Here we have an operation of all elements not greater than the mean (lesser than the mean):

In [52]:
a[~(a > a.mean())]

array([0, 1])

Applying the OR Boolean operator:

In [53]:
a[(a ==0) | (a ==1)]

array([0, 1])

Applying the And Boolean Operator:

In [54]:
a[(a <= 2) & (a % 2 == 0)]

array([0, 2])

In [55]:
A = np.random.randint(100, size=(3,3))

In [56]:
A

array([[82, 87, 39],
       [32, 36, 52],
       [65, 24, 63]])

In [57]:
A[np.array([
    [True,False,True],
    [False,True,False],
    [True,False,True]
])]

array([82, 39, 36, 65, 63])

In [59]:
A > 30

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True, False,  True]])

In [60]:
A[A > 30]

array([82, 87, 39, 32, 36, 52, 65, 63])

# Linear Algebra

In [61]:
A = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [62]:
B = np.array([
    [6, 5],
    [4, 3],
    [2, 1]
])

In [63]:
A.dot(B)

array([[20, 14],
       [56, 41],
       [92, 68]])

In [64]:
A @ B

array([[20, 14],
       [56, 41],
       [92, 68]])

In [65]:
B.T

array([[6, 4, 2],
       [5, 3, 1]])

In [66]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [67]:
B.T @ A

array([[36, 48, 60],
       [24, 33, 42]])

# Size of Objects in Memory

## Int, floats

In [68]:
# An integer in Python is > 24 bytes
sys.getsizeof(1)

28

In [69]:
# Longs are even larger
sys.getsizeof(10**100)

72

In [70]:
# Numpy size is much smaller
np.dtype(int).itemsize

4

In [72]:
np.dtype(float).itemsize

8

# Lists are even larger

In [73]:
# A one-element list
sys.getsizeof([1])

64

In [75]:
# An array of one element in numpy
np.array([1]).nbytes

4

# And Perfomance is also important

In [76]:
l = list(range(1000))

In [77]:
a = np.arange(1000)

In [78]:
%time np.sum(a ** 2)

Wall time: 0 ns


332833500

In [79]:
%time sum([x ** 2 for x in l])

Wall time: 0 ns


332833500

# Useful Numpy functions

## random

In [80]:
np.random.random(size=2)

array([0.10310501, 0.7352167 ])

In [81]:
np.random.normal(size=2)

array([-0.19261772, -0.09312332])

In [82]:
np.random.rand(2, 4)

array([[0.64635121, 0.05628485, 0.72035061, 0.05840327],
       [0.43051061, 0.12885423, 0.3991408 , 0.03393277]])

## arange

In [83]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [84]:
np.arange(5, 10)

array([5, 6, 7, 8, 9])

In [85]:
np.arange(0, 1, .1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

## reshape

In [86]:
np.arange(10).reshape(2, 5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [87]:
np.arange(10).reshape(5, 2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

## linspace

In [88]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [89]:
np.linspace(0, 1, 20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [90]:
np.linspace(0, 1, 20, False)

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95])